Feat/explore workspace
mlcraft-io/client-v2 pull request #46
Opened 2023-10-06 14:18 UTC by DefK1lla

2023-10-09 10:04 UTC, ifokeev commented on src/components/ExploreCubes/index.stories.tsx
> +    Airports: {
too much data, should be saved somewhere like mocks

2023-10-09 10:04 UTC, ifokeev commented on src/components/ExploreCubesSection/index.stories.tsx
> +  selectedMembers: {
too much data, should be saved somewhere like mocks

2023-10-09 10:04 UTC, ifokeev commented on src/components/ExploreCubesSection/index.tsx
> +  return <div className={s.root}>{SHOWN_CATEGORIES.map(getCategory)}</div>;
why this needed? style changed?

2023-10-09 10:09 UTC, ifokeev commented on src/components/ExploreDataSection/index.stories.tsx
> +  selectedQueryMembers: {
too much data, should be saved somewhere like mocks

2023-10-09 10:09 UTC, ifokeev commented on src/components/ExploreFiltersSection/index.stories.tsx
> +  availableQueryMembers: {
too much data, should be saved somewhere like mocks

2023-10-09 10:10 UTC, ifokeev commented on src/components/ExploreWorkspace/index.stories.tsx
> +  meta: [
too much data, should be saved somewhere like mocks

2023-10-09 10:10 UTC, ifokeev commented on src/components/ExploreWorkspace/index.tsx
> +  basePath: string;
not used anywhere

2023-10-09 14:53 UTC, DefK1lla commented on src/components/ExploreCubesSection/index.tsx
> +  return <div className={s.root}>{SHOWN_CATEGORIES.map(getCategory)}</div>;
yes, background

2023-10-12 10:56 UTC, ifokeev requested changes

2023-10-12 10:56 UTC, ifokeev commented on src/components/ExploreDataSection/index.stories.tsx
> +  }, [args.queryState.columns, args.queryState.rows, settings]);
code duplication

2023-10-12 10:56 UTC, ifokeev commented on src/components/ExploreFiltersSection/index.stories.tsx
> +  });
code duplication

2023-10-12 19:15 UTC, ifokeev approved these changes

2023-10-12 19:15 UTC, merged