feat: query logs api
mlcraft-io/client-v2 pull request #52
Opened 2023-10-18 15:05 UTC by DefK1lla

2023-10-18 15:19 UTC, ifokeev commented on src/components/QueryFilter/index.tsx
> +const QueryFilter: FC<QueryFilterProps> = ({
`QueryFilters`

2023-10-18 15:20 UTC, ifokeev commented on src/components/QueryLogsTable/index.stories.tsx
> +        },
all empty fields could be removed

2023-10-18 15:21 UTC, ifokeev commented on src/components/QueryLogsTable/index.stories.tsx
> +  ],
please keep only valuable data

2023-10-18 15:23 UTC, ifokeev commented on config/routes.ts
> +            path: "/logs/query",
should be link in the menu too

2023-10-18 17:01 UTC, Libertonius requested changes

2023-10-18 19:15 UTC, ifokeev requested changes

2023-10-18 19:15 UTC, ifokeev commented on src/pages/QueryLogs/index.tsx
> +  const basePath = withAuthPrefix("/logs/requests");
why url is `/logs/requests/` but page url is `/logs/query`? Base path should be the same

2023-10-18 19:15 UTC, ifokeev commented on src/components/QueryFilters/index.tsx
> +const QueryFilters: FC<QueryFiltersProps> = ({
date input is not keeping selected value, should keep on select

2023-10-18 19:15 UTC, ifokeev commented on src/components/QueryLogsTable/index.tsx
> +      onRow={(r) => ({
on row hover should have `cursor: pointer`, because it's clickable

2023-10-19 11:35 UTC, ifokeev approved these changes

2023-10-20 09:09 UTC, Libertonius approved these changes

2023-10-20 09:10 UTC, merged